### PR TITLE
fix #79: 2022.3.X Breaks dropdown

### LINKED ISSUE #79: Проблема с выпадающим списком
Добрый день! Выпадающие списки развернуты. подскажите пожалуйста как исправить.

### PR DESCRIPTION
**Pull request by regevbr**
fix: #79 

So according to https://developers.home-assistant.io/blog/2022/02/18/paper-elements/ all paper elements are not supported anymore starting 2022.3 and they recommend using mwc components instead. The current behavior is a complete breakdown of the dropdown menus.

The fix is based on my work on https://github.com/artem-sedykh/mini-climate-card/pull/67, but since I don't have a way to test it, I would appreciate the comments from the community.

Need to note that this is probably will not work on previous versions of HA and as such, I added a comment in the readme and updated the version to 3 (as this is a breaking change).

@artem-sedykh if you can take it from here it will be awesome :-)

To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/4e91349b63f1a0700f312ce34dbad233)

### CODE REVIEW

**Comment by regevbr** [comment]
@anhnvme as per your request - I would appreciate it if you can thoroughly test it and let me know if you see any issues.

Thanks,

**Comment by anhnvme** [comment]
> @anhnvme as per your request - I would appreciate it if you can thoroughly test it and let me know if you see any issues.
> 
> Thanks,

wow, it's amazing. thank you so much, it's work perfectly !

**Comment by anhnvme** [comment]
image
@regevbr hello, just little bit, but i see color not same as theme. i see mini AC you fix without change color. but mini humidifier changed color, can you fix it, it's not urgent. but when u have time, please help me check it

thank you so much

**Comment by regevbr** [comment]
> image @regevbr hello, just little bit, but i see color not same as theme. i see mini AC you fix without change color. but mini humidifier changed color, can you fix it, it's not urgent. but when u have time, please help me check it
> 
> thank you so much

@anhnvme I'm not sure how the theming works in HA, so I gave it a try and updated the gist with the hot fix, can you use it and let me know if that works? if not I have another option in mind to fix

**Comment by anhnvme** [comment]
> > image @regevbr hello, just little bit, but i see color not same as theme. i see mini AC you fix without change color. but mini humidifier changed color, can you fix it, it's not urgent. but when u have time, please help me check it
> > thank you so much
> 
> @anhnvme I'm not sure how the theming works in HA, so I gave it a try and updated the gist with the hot fix, can you use it and let me know if that works? if not I have another option in mind to fix

Thank  you, i just update, but it's not working. Take time, it's not urgent bro

**Comment by anhnvme** [comment]
> > image @regevbr hello, just little bit, but i see color not same as theme. i see mini AC you fix without change color. but mini humidifier changed color, can you fix it, it's not urgent. but when u have time, please help me check it
> > thank you so much
> 
> @anhnvme I'm not sure how the theming works in HA, so I gave it a try and updated the gist with the hot fix, can you use it and let me know if that works? if not I have another option in mind to fix

image
look like it's more blue :D. can you show me where i can change hex color code ?

**Comment by regevbr** [comment]
> fix: #79
> 
> So according to https://developers.home-assistant.io/blog/2022/02/18/paper-elements/ all paper elements are not supported anymore starting 2022.3 and they recommend using mwc components instead. The current behavior is a complete breakdown of the dropdown menus.
> 
> The fix is based on my work on [artem-sedykh/mini-climate-card#67](https://github.com/artem-sedykh/mini-climate-card/pull/67), but since I don't have a way to test it, I would appreciate the comments from the community.
> 
> Need to note that this is probably will not work on previous versions of HA and as such, I added a comment in the readme and updated the version to 3 (as this is a breaking change).
> 
> @artem-sedykh if you can take it from here it will be awesome :-)
> 
> To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/4e91349b63f1a0700f312ce34dbad233)

Can you try again - I reverted all changes to CSS so nothing should be harmed

**Comment by anhnvme** [comment]
> > fix: #79
> > So according to https://developers.home-assistant.io/blog/2022/02/18/paper-elements/ all paper elements are not supported anymore starting 2022.3 and they recommend using mwc components instead. The current behavior is a complete breakdown of the dropdown menus.
> > The fix is based on my work on [artem-sedykh/mini-climate-card#67](https://github.com/artem-sedykh/mini-climate-card/pull/67), but since I don't have a way to test it, I would appreciate the comments from the community.
> > Need to note that this is probably will not work on previous versions of HA and as such, I added a comment in the readme and updated the version to 3 (as this is a breaking change).
> > @artem-sedykh if you can take it from here it will be awesome :-)
> > To use the fix until it is released, follow the steps I made [here](https://gist.github.com/regevbr/4e91349b63f1a0700f312ce34dbad233)
> 
> Can you try again - I reverted all changes to CSS so nothing should be harmed

image
Finally, It's working perfect ! Thank you bro !!!!!!!!

**Comment by regevbr** [comment]
@anhnvme I just made another adjument, do you mind updating it on your end just to make sure everything still works?

**Comment by anhnvme** [comment]
> @anhnvme I just made another adjument, do you mind updating it on your end just to make sure everything still works?

hello, i just update. Everything still working perfectly

**Pull request merged**
